sudo: required
services:
        - docker

before_install:
        - docker build -t kuperiu/docker-react -f Dockerfile.dev .

script:
        - docker run kuperiu/docker-react npm run test -- --coverage
